name: release-docker

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: [Releases]
    types: [completed]
  workflow_dispatch:
    inputs:
      manual:
        type: boolean
        default: true

env:
  actor: unickcheng

jobs:
  docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }} || ${{ inputs.manual }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.actor }}/openai-proxy
            ghcr.io/${{ env.actor }}/openai-proxy
          tags: |
            type=raw,enable={{is_default_branch}},value=latest
            type=semver,pattern={{version}}
            type=edge,branch=main

      - name: Login to GitHub Package
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
